NevulaForo/Models/DB/Publication.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NevulaForo.Models.DB;

public partial class Publication
{
    public int Id { get; set; }

    public int IdUser { get; set; }

    [Required(ErrorMessage = "Debe ingresar un título.")]
    [MinLength(5, ErrorMessage = "El título debe tener entre 5 y 250 caracteres.")]
    [MaxLength(250, ErrorMessage = "El título debe tener entre 5 y 250 caracteres.")]
    public string Title { get; set; } = null!;

    [Required(ErrorMessage = "Debe ingresar un contenido.")]
    [MinLength(30, ErrorMessage = "El contenido del post debe tener entre 30 y 1750 caracteres.")]
    [MaxLength(1750, ErrorMessage = "El contenido del post debe tener entre 30 y 1750 caracteres.")]
    public string Description { get; set; } = null!;

    public DateTime CreatedAt { get; set; } = DateTime.Now;

    public DateTime? DeletedAt { get; set; } 

    public bool? IsBanned { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual User IdUserNavigation { get; set; } = null!;
}

NevulaForo/Controllers/PublicationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

using NevulaForo.Models;
using NevulaForo.Models.DB;
using NevulaForo.Models.ViewModels;
using System.Security.Claims;
using System.Linq;
using NevulaForo.Services.Contract;
using System;
using System.Text.RegularExpressions;
using NevulaForo.Resources;
using System.Security.Policy;

namespace NevulaForo.Controllers
{
    public class PublicationController : Controller
    {

        private readonly NevulaContext _DBContext;

        public PublicationController(NevulaContext dbContext)
        {
            _DBContext = dbContext;
        }


        [HttpGet]
        public IActionResult Index(int IdPublication)
        {
            PublicationDedicatedVM oPublicationDedicated = new PublicationDedicatedVM()
            {
                // No verifico que el Comments (del oPublication) traiga los comentarios validos (sin eliminar ni usuario creador eliminado), ya que para todo lo relacionado a comentarios uso el oComments
                oPublication = _DBContext.Publications
                                .Include(u => u.IdUserNavigation)
                                    .ThenInclude(u => u.UserRoles)
                                .Where(p => p.Id == IdPublication && p.DeletedAt == null && p.IsBanned == null && p.IdUserNavigation.DeletedAt == null && p.IdUserNavigation.IsBanned == null)
                                .FirstOrDefault(),
                oComments = _DBContext.Comments
                                .Include(u => u.IdUserNavigation)
                                    .ThenInclude(u => u.UserRoles)
                                .Include(c => c.IdFatherCommentNavigation)
                                .Where(c => c.DeletedAt == null && c.IdPublication == IdPublication && c.IdUserNavigation.DeletedAt == null && c.IdUserNavigation.IsBanned == null)
                                .OrderByDescending(c => c.CreatedAt)
                                .ToList()
            };

            if (oPublicationDedicated.oPublication != null)
            {
                ClaimsPrincipal claimUser = HttpContext.User;
                string username = "";

                if (claimUser.Identity.IsAuthenticated)
                {
                    username = claimUser.Claims.Where(c => c.Type == ClaimTypes.NameIdentifier).Select(c => c.Value).SingleOrDefault();
                }

                ViewData["username"] = username;

                return View(oPublicationDedicated);

            } else
            {
                //404
                return NotFound();
            }

        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, Authorize]
        public async Task<JsonResult> CreateApi([FromBody] CreatePublicationVM viewmodel)
        {
            int IdUser = Convert.ToInt32(HttpContext.User.FindFirstValue("Id"));

            if (!ModelState.IsValid)
            {
                var errors = ModelState.Where(x => x.Value.Errors.Any())
                               .ToDictionary(
                                   kvp => kvp.Key,
                                   kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToList()
                               );

                return Json(new { success = false, errors = errors });
            }


            User user = _DBContext.Users.Where(u => u.Id == IdUser && u.DeletedAt == null && u.IsBanned == null).ToList().First();

            Publication model = new Publication()
            {
                IdUser = IdUser,
                Title = viewmodel.Title,
                Description = Utilities.ReduceLineBreaks(viewmodel.Description),
                CreatedAt = DateTime.Now,
                DeletedAt = null,
                IdUserNavigation = user

            };

            _DBContext.Add(model);
            await _DBContext.SaveChangesAsync();

            return Json(new { success = true, redirectUrl = $"/Account/Index?IdUser={IdUser}" }); 
        }


        [HttpGet, Authorize]
        public IActionResult Edit(int IdPublication)
        {
            try
            {
                int IdUser = Convert.ToInt32(HttpContext.User.FindFirstValue("Id"));

                Publication? modelPublication = _DBContext.Publications.FirstOrDefault(p => p.Id == IdPublication && p.IdUser == IdUser);
                
                if (modelPublication != null)
                {
                    CreatePublicationVM viewmodel = new CreatePublicationVM()
                    {
                        Id = modelPublication.Id,
                        Title = modelPublication.Title,
                        Description = modelPublication.Description
                    };

                    return View(viewmodel);

                } else
                {
                    throw new InvalidOperationException("No existe la publicacion o esta eliminada");
                }

            } catch (Exception ex) 
            {
                //404
                return NotFound();
            }
        }

        [HttpPost, Authorize]
        public async Task<JsonResult> EditApi([FromBody] CreatePublicationVM viewmodel)
        {
            viewmodel.Id = Utilities.valueParameterId(new Uri(Request.Headers["Referer"].ToString()), "IdPublication");

            if(viewmodel.Id == 0)
            {
                return Json(new { success = false, errors = new List<string> { "Error al intentar editar la publicación" } });
            }

            int IdUser = Convert.ToInt32(HttpContext.User.FindFirstValue("Id"));
            Publication? model = _DBContext.Publications.Where(p => p.Id == viewmodel.Id && p.IdUser == IdUser && p.DeletedAt == null && p.IsBanned == null).ToList().FirstOrDefault();

            if (model != null && (viewmodel.Title != model.Title || viewmodel.Description != model.Description))
            {

                if (!ModelState.IsValid)
                {
                    var errors = ModelState.Where(x => x.Value.Errors.Any())
                               .ToDictionary(
                                   kvp => kvp.Key,
                                   kvp => kvp.Value.Errors.Select(e => e.ErrorMessage).ToList()
                               );

                    return Json(new { success = false, errors = errors });
                }

                User user = _DBContext.Users.Where(u => u.Id == IdUser && u.DeletedAt == null && u.IsBanned == null).ToList().First();

                model.Title = viewmodel.Title;
                model.Description = viewmodel.Description;

                _DBContext.Update(model);
                await _DBContext.SaveChangesAsync();

                return Json(new { success = true, redirectUrl = $"/Publication/Index?IdPublication={model.Id}" });
            }

            //404
            return Json(new { success = false, errors = new List<string> { "Error al intentar editar la publicación" } });
        }

        [HttpGet, Authorize]
        public async Task<JsonResult> DeleteApi(int IdPublication)
        {
            int IdUser = Convert.ToInt32(HttpContext.User.FindFirstValue("Id"));

            Publication? publication = _DBContext.Publications.FirstOrDefault(p => p.Id == IdPublication && p.IdUser == IdUser && p.DeletedAt == null && p.IsBanned == null);

            if (publication != null)
            {
                publication.DeletedAt = DateTime.Now;

                _DBContext.Update(publication);
                await _DBContext.SaveChangesAsync();

                var referer = Request.Headers["Referer"].ToString();
                Uri uri = new Uri(referer);
                string refererAbsolutePath = uri.AbsolutePath;

                if (refererAbsolutePath == "/Publication/Index")
                {
                    return Json(new { success = true, redirectUrl = $"/Account/Index?IdUser={IdUser}" });
                } else
                {
                    return Json(new { success = true });
                }

            }

            return Json(new { success = false, error = "Error al intentar eliminar la publicacion" });
        }


        [HttpGet]
        public IActionResult Search(SearchVM viewmodel)
        {

            if (viewmodel.For == "posts")
            {
                viewmodel.Publications = _DBContext.Publications
                                                .Include(u => u.IdUserNavigation)
                                                    .ThenInclude(u => u.UserRoles)
                                                .Include(c => c.Comments)
                                                .Where(p => p.DeletedAt == null && p.IsBanned == null && p.IdUserNavigation.DeletedAt == null && p.IdUserNavigation.IsBanned == null && EF.Functions.Like(p.Title, $"%{viewmodel.Search}%"))
                                                .Select(p => new Publication
                                                {
                                                    Id = p.Id,
                                                    IdUser = p.IdUser,
                                                    Title = p.Title,
                                                    Description = p.Description,
                                                    CreatedAt = p.CreatedAt,
                                                    Comments = p.Comments.Where(comment => comment.DeletedAt == null && comment.IdUserNavigation.DeletedAt == null && comment.IdUserNavigation.IsBanned == null).ToList(),
                                                    IdUserNavigation = p.IdUserNavigation
                                                })
                                                .OrderByDescending(p => p.CreatedAt)
                                                .ToList();
            } else
            {

NevulaForo/Views/Publication/Create.cshtml
@model NevulaForo.Models.ViewModels.CreatePublicationVM;
@{
    ViewData["Title"] = "Crear publicación";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/css/community.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/create_publication.css" asp-append-version="true" />
}

<article class="main__containers-community">
    <form method="POST" id="formCreatePost">

        <div asp-validation-summary="ModelOnly"></div>

        <div class="container__title">
            <a href="javascript:history.back()" class="button_back"><i class="bi bi-arrow-left-short"></i></a>
            <div id="title_page">
                <h2>Creá una publicación</h2>
            </div>
        </div>

        <div class="container__input-title">
            <h3>Título</h3>
            <textarea class="post_textarea" name="Title" asp-for="Title" id="title" placeholder="Introduce un título" maxlength="250"></textarea>
            <span asp-validation-for="Title"></span>
        </div>

        <div class="container__input-content">
            <h3>Contenido</h3>
            <textarea class="post_textarea" name="Description" asp-for="Description" id="description" placeholder="Introduce texto" maxlength="1750"></textarea>
            <span asp-validation-for ="Description"></span>
        </div>

        <div class="container__inputs-finally">
            <button class="button_reset" type="reset">Descartar</button>
            <button class="button_submit" type="submit">Publicar</button>
        </div>
    </form>

</article>


@section Scripts {
    <script src="~/js/api/create_post.js" asp-append-version="true"></script>
}

NevulaForo/Views/Publication/Edit.cshtml
@model NevulaForo.Models.ViewModels.CreatePublicationVM;
@{
    ViewData["Title"] = "Editar publicación";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/css/community.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/create_publication.css" asp-append-version="true" />
}

<article class="main__containers-community">
    <form method="POST" id="formEditPost">

        <div asp-validation-summary="ModelOnly"></div>

        <div class="container__title">
            <a href="javascript:history.back()" class="button_back"><i class="bi bi-arrow-left-short"></i></a>
            <div id="title_page">
                <h2>Editá tu publicación</h2>
            </div>
        </div>

        <div class="container__input-title">
            <h3>Título</h3>
            <textarea class="post_textarea" name="Title" asp-for="Title"  id="title" placeholder="Introduce un título" maxlength="250"></textarea>
            <span asp-validation-for="Title"></span>
        </div>

        <div class="container__input-content">
            <h3>Contenido</h3>
            <textarea class="post_textarea" name="Description" asp-for="Description"  id="description" placeholder="Introduce texto" maxlength="1750"></textarea>
            <span asp-validation-for="Description"></span>
        </div>

        <div class="container__inputs-finally">
            <button class="button_reset" type="reset">Descartar</button>
            <button class="button_submit" type="submit" id="submit_edit-post" disabled>Confirmar</button>
        </div>
    </form>

</article>

@section Scripts {
    <script src="~/js/api/edit_post.js" asp-append-version="true"></script>
}

NevulaForo/Views/Publication/Index.cshtml
@model NevulaForo.Models.ViewModels.PublicationDedicatedVM

@using NevulaForo.Resources;
@using NevulaForo.Services.Implementation;
@inject UserService UserService;
@{
    ViewData["Title"] = Model.oPublication.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    var userIdClaim = User.FindFirst("Id");
    int IdUser = Convert.ToInt32(userIdClaim?.Value);
}

@section Styles {
    <link rel="stylesheet" href="~/css/community.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/publication.css" asp-append-version="true" />
}

<!-- Publicacion -->
<article class="main__containers-community">
    <div class="container__info">
        <div class="container__profile-pic">
            <a asp-route-IdUser="@Model.oPublication.IdUser" asp-controller="Account" asp-action="Index">
                <img src="@UserService.GetUserProfileImagePath(Model.oPublication.IdUser)" alt="">
            </a>
        </div>

        <div class="container__username">
            <a asp-route-IdUser="@Model.oPublication.IdUser" asp-controller="Account" asp-action="Index">@Model.oPublication.IdUserNavigation.Username</a>
        </div>

        @if(Model.oPublication.IdUserNavigation.UserRoles.First().IdRole == 2)
        {
            <!-- Esto depende si esta o no verificado -->
            <div class="container__verify" id="container__verify-1">
                <span class="verify">VERIFICADO</span>
                <span class="small-verify">V</span>
                <span class="popup-verify" id="popup-verify-1">Esta persona forma parte de Nevula</span>
            </div>
        }

        <span class="separator__info">·</span>

        <div class="container__date">
            <span>@Utilities.StylizeDate(Model.oPublication.CreatedAt)</span>
        </div>
    </div>

    <div class="container__content-post">
        <h2 class="title--post">@Model.oPublication.Title</h2>
        <p class="content--post">@Model.oPublication.Description</p>
        <div class="container__imgs"></div>
    </div>

    <div class="container__feedback">
        <div>
            <p class="feedback__comments ">
                <i class="bi bi-chat"></i>
                <span id="span_cant-comments" >@Model.oComments.Count @((@Model.oComments.Count == 1) ? "Comentario" : "Comentarios")</span>
            </p>
        </div>

        @if (Model.oPublication.IdUser == IdUser)
        {
            <div>
                <a class="post__edit" asp-route-IdPublication="@Model.oPublication.Id" asp-controller="Publication" asp-action="Edit"><i class="bi bi-pencil-square"></i> </a>
                <button type="button" class="post__delete" id="delete_post"><i class="bi bi-trash3"></i> </button>
            </div>
        }
    </div>

</article>


<!-- Formulario para publicar comentarios -->
<article class="main__containers-community container_form-comment">
    <form method="POST" id="formCreateComment">
        @Html.AntiForgeryToken()

        <input type="hidden" value="@Model.oPublication.Id" name="IdPublication" id="IdPublication">
        <input type="hidden" value="" name="IdFatherComment" id="IdFatherComment">

        <div class="container__profile-pic" id="form_comment-pic">
            <img src="@UserService.GetUserProfileImagePath(IdUser)" alt="Tu foto de perfil">
        </div>

        <div class="container__profile-text">
            <p>Responder desde <span class="span_username">@ViewData["username"]</span></p>
        </div>

        <div class="container__inputs-form">
            <div class="container__input-content">
                <textarea class="post_textarea" name="Description" id="Description" placeholder="Escribe una respuesta" maxlength="1750"></textarea>
                <span data-valmsg-for="Description"></span>
            </div>

            <div class="container__inputs-finally">
                <button class="button_submit" type="submit">Publicar</button>
            </div>
        </div>
    </form>
</article>



<!-- Comentarios -->
@if(Model.oComments.Count > 0)
{
    <article class="main__containers-community" id="container__comments">
        <h3 class="title_answer" id="title_answer">Respuestas</h3>

        @foreach (var comment in Model.oComments)
        {
            <div class="container__comment" id="comment_@comment.Id">
                <div class="container__info">
                    <div class="comment__profile-pic">
                        <a asp-route-IdUser="@comment.IdUser" asp-controller="Account" asp-action="Index">
                            <img src="@UserService.GetUserProfileImagePath(comment.IdUser)" alt="">
                        </a>
                    </div>

                    <div class="container__username">
                        <a asp-route-IdUser="@comment.IdUser" asp-controller="Account" asp-action="Index">@comment.IdUserNavigation.Username</a>
                    </div>

                    @if(comment.IdUserNavigation.UserRoles.First().IdRole == 2)
                    {
                        <!-- Esto depende si esta o no verificado -->
                        <div class="container__verify" id="container__verify-2">
                            <span class="verify">VERIFICADO</span>
                            <span class="small-verify">V</span>
                            <span class="popup-verify" id="popup-verify-2">Esta persona forma parte de Nevula</span>
                        </div>
                    }

                    <span class="separator__info">·</span>

                    <div class="container__date">
                        <span>@Utilities.StylizeDate(comment.CreatedAt)</span>
                    </div>
                </div>

                <div class="container__answer">
                    @if(comment.IdFatherComment != null)
                    {
                        <div class="container__content-cited">
                            @if(comment.IdFatherCommentNavigation.DeletedAt == null)
                            {
                                <p class="title--cited">Comentario de <a class="username_quoted" href="#comment_@comment.IdFatherCommentNavigation.Id">@@@comment.IdFatherCommentNavigation.IdUserNavigation.Username</a></p>
                                <p class="content--cited">@comment.IdFatherCommentNavigation.Description</p>
                            } else
                            {
                                <p class="content--cited" style="font-weight: 600;">¡Lo sentimos! El comentario citado fue eliminado :(</p>
                            }
                        </div>
                    }
                    <div class="container__content-post">
                        <p class="content--post" id="comment_description-@comment.Id">@comment.Description</p>
                        <div class="container__imgs"></div>
                    </div>
                </div>



                <div class="container__feedback">
                    <div>
                        <a href="#" class="feedback__aswer-comments" id="answer_comment_@comment.Id" data-comment-id="@comment.Id" data-comment-username="@comment.IdUserNavigation.Username">Responder</a>
                    </div>

                    @if (comment.IdUser == IdUser)
                    {
                        <div>
                            <button type="button" class="comment__delete" id="delete_comment-@comment.Id" ><i class="bi bi-trash3"></i> </button>
                        </div>
                    }
                </div>

            </div>
        }

    </article>

}


@section Scripts {
    <script src="~/js/community.js" asp-append-version="true"></script>
    <script src="~/js/publication.js" asp-append-version="true"></script>
    <script src="~/js/api/comments.js" asp-append-version="true"></script>

    @if (Model.oPublication.IdUser == IdUser)
    {
        <script src="~/js/api/delete_post.js" asp-append-version="true"></script>
    }
}

NevulaForo/Views/Publication/Search.cshtml
@model NevulaForo.Models.ViewModels.SearchVM

@using NevulaForo.Resources;
@using NevulaForo.Services.Implementation;
@inject UserService UserService;
@{

    ViewData["Title"] = (Model.For == "posts") ? "Buscar publicaciones" : "Buscar cuentas";
    ViewData["Section"] = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/css/community.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/search.css" asp-append-version="true" />
}

<!--ASIDE EN LAYOUT ("~/Views/Shared/_Layout.cshtml")-->
<aside class="aside__menu-searches main__containers-community">
    <ul class="submenu__searches">
        <li class="submenu__searches-item">
            <a class="btn_search-posts " asp-controller="Publication" asp-action="Search" asp-route-search="@Model.Search" asp-route-for="posts">PUBLICACIONES</a>
        </li>
        <li class="submenu__searches-item">
            <a class="btn_search-accounts " asp-controller="Publication" asp-action="Search" asp-route-search="@Model.Search" asp-route-for="accounts">CUENTAS</a>
        </li>
    </ul>
</aside>

<main class="container" role="main">
    @if ((Model.Users != null && Model.Users.Count > 0) || (Model.Publications != null && Model.Publications.Count > 0))
    {
        @if (Model.For == "posts")
        {
            <div>
                @foreach (var publication in Model.Publications)
                {
                    <article class="main__containers-community">

                        <div class="container__info">
                            <div class="container__profile-pic">
                                <a asp-route-IdUser="@publication.IdUser" asp-controller="Account" asp-action="Index">
                                    <img src="@UserService.GetUserProfileImagePath(publication.IdUser)" alt="">
                                </a>
                            </div>

                            <div class="container__username">
                                <a asp-route-IdUser="@publication.IdUser" asp-controller="Account" asp-action="Index">@publication.IdUserNavigation.Username</a>
                            </div>

                            @if (publication.IdUserNavigation.UserRoles.First().IdRole == 2)
                            {
                                <!-- Esto depende si esta o no verificado -->
                                <div class="container__verify" id="container__verify-1">
                                    <span class="verify">VERIFICADO</span>
                                    <span class="small-verify">V</span>
                                    <span class="popup-verify" id="popup-verify-1">Esta persona forma parte de Nevula</span>
                                </div>
                            }

                            <span class="separator__info">·</span>

                            <div class="container__date">
                                <span>@Utilities.StylizeDate(publication.CreatedAt)</span>
                            </div>
                        </div>

                        <div class="container__content-post">
                            <h2 class="title--post">@publication.Title</h2>
                            <p class="content--post">@publication.Description</p>
                            <div class="container__imgs"></div>
                        </div>

                        <div class="container__feedback">
                            <div>
                                <a class="feedback__comments" asp-route-IdPublication="@publication.Id" asp-controller="Publication" asp-action="Index">
                                    <i class="bi bi-chat"></i>
                                    <span>@publication.Comments.Count @((@publication.Comments.Count == 1) ? "Comentario" : "Comentarios")</span>
                                </a>
                            </div>
                        </div>

                    </article>
                }
            </div>

        }
        else if (Model.For == "accounts")
        {
            <div>
                @foreach (var account in Model.Users)
                {
                    <article href="#" class="container__perfil">
                        <div class="container_info">
                            <div class="container_info-data">
                                <div class="container__profile-picture">
                                    <img src="@UserService.GetUserProfileImagePath(account.Id)" alt="">
                                </div>
                                <div class="container_name">
                                    @if (account.Name != null || account.Surname != null)
                                    {
                                        <a asp-controller="Account" asp-action="Index" asp-route-IdUser="@account.Id">@account.Name @account.Surname</a>
                                        <span class="separator__info">·</span>
                                    }
                                    <a asp-controller="Account" asp-action="Index" asp-route-IdUser="@account.Id" class="text-username">@@@account.Username</a>
                                </div>

                                @if (account.UserRoles.First().IdRole == 2)
                                {
                                    <!-- Esto depende si esta o no verificado -->
                                    <div class="container__verify" id="container__verify-1">
                                        <span class="verify">VERIFICADO</span>
                                        <span class="small-verify">V</span>
                                        <span class="popup-verify" id="popup-verify-1">Esta persona forma parte de Nevula</span>
                                    </div>
                                }
                            </div>
                        </div>
                    </article>
                }
            </div>
        }

    } else
    {
        <p class="search__not-results">No se encontraron resultados para la busqueda "<span>@Model.Search</span>".</p>
    }
</main>

@section Scripts {
    <script src="~/js/community.js" asp-append-version="true"></script>
    <script src="~/js/search.js" asp-append-version="true"></script>
}